/**
 * Daily Wrap-Up logic (ported from scripts/daily-wrap-up.sh).
 * Parses notes text into Done / Doing / Next.
 */

const MAX_BULLETS = 5;

const DONE_HINT =
  /\b(complet(ed|e)?|finish(ed)?|done|pushed|shipped|merged|submit(ted)?|fixed|closed|deployed|wrote|uploaded)\b/i;
const DOING_HINT =
  /\b(working on|in progress|building|setup|setting up|wip|currently|still|debugging|writing|drafting|module)\b/i;
const NEXT_HINT =
  /\b(next|todo|follow[- ]?up|tomorrow|need to|should|plan to|later|loose ends?)\b/i;

function normalizeBullet(text) {
  return String(text || "")
    .replace(/^[-*•]\s+/, "")
    .replace(/^\d+[.)]\s+/, "")
    .replace(/\s+/g, " ")
    .trim();
}

function dedupe(items) {
  const seen = new Set();
  const out = [];
  for (const item of items) {
    const key = item.toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

function cap(items, fallback) {
  const cleaned = dedupe(items).slice(0, MAX_BULLETS);
  return cleaned.length ? cleaned : [fallback];
}

function classifyLooseBullet(bullet) {
  // Prefer follow-ups before completed-work hints ("need to submit" ≠ done).
  if (NEXT_HINT.test(bullet)) return "next";
  if (DONE_HINT.test(bullet)) return "done";
  if (DOING_HINT.test(bullet)) return "doing";
  return "next";
}

function parseNotes(raw) {
  const lines = String(raw || "").split(/\r?\n/);
  let inSection = "";
  let done = [];
  let doing = [];
  let next = [];
  let loose = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Skip title lines like "# Today's notes"
    if (/^#\s+/.test(trimmed) && !/^##\s+/.test(trimmed)) continue;

    if (/^##\s*(Morning|Done|Completed)/i.test(trimmed)) {
      inSection = "done";
      continue;
    }
    if (/^##\s*(Afternoon|Doing|In progress|WIP)/i.test(trimmed)) {
      inSection = "doing";
      continue;
    }
    if (/^##\s*(Next|Loose ends|Follow-?ups?|Tomorrow|Todo)/i.test(trimmed)) {
      inSection = "next";
      continue;
    }

    // Headings that aren't wrap-up sections — ignore
    if (/^##\s+/.test(trimmed)) {
      inSection = "";
      continue;
    }

    const bulletMatch = trimmed.match(/^([-*•]|\d+[.)])\s+(.+)$/);
    const bullet = bulletMatch
      ? normalizeBullet(bulletMatch[2])
      : inSection
        ? normalizeBullet(trimmed)
        : "";

    if (!bullet) {
      // Freeform paragraph with no section — treat as a loose item
      if (!inSection && trimmed.length > 3 && !/^#+/.test(trimmed)) {
        loose.push(normalizeBullet(trimmed));
      }
      continue;
    }

    if (inSection === "done") done.push(bullet);
    else if (inSection === "doing") doing.push(bullet);
    else if (inSection === "next") next.push(bullet);
    else loose.push(bullet);
  }

  for (const item of loose) {
    const bucket = classifyLooseBullet(item);
    if (bucket === "done") done.push(item);
    else if (bucket === "doing") doing.push(item);
    else next.push(item);
  }

  return {
    done: cap(done, "(see notes for today)"),
    doing: cap(doing, "(nothing flagged in progress)"),
    next: cap(next, "Review notes and plan tomorrow"),
  };
}

function formatWrapup({ done, doing, next }, date, trigger = "web") {
  const stamp = new Date().toLocaleString("en-GB", {
    timeZone: "Africa/Nairobi",
    hour12: false,
  });
  return [
    `# Daily Wrap-Up — ${date}`,
    "",
    "## Done",
    ...done.map((b) => `- ${b}`),
    "",
    "## Doing",
    ...doing.map((b) => `- ${b}`),
    "",
    "## Next",
    ...next.map((b) => `- ${b}`),
    "",
    "---",
    `*Generated by daily-wrap-up (trigger: ${trigger}) at ${stamp} EAT*`,
  ].join("\n");
}

function runWrapup(notesText, options = {}) {
  const date =
    options.date ||
    new Date().toLocaleDateString("en-CA", { timeZone: "Africa/Nairobi" });
  const parsed = parseNotes(notesText);
  return formatWrapup(parsed, date, options.trigger || "web");
}

module.exports = { parseNotes, formatWrapup, runWrapup, MAX_BULLETS };
