/**
 * Daily Wrap-Up logic (ported from scripts/daily-wrap-up.sh).
 * Parses notes text into Done / Doing / Next.
 */

function parseNotes(raw) {
  const lines = String(raw || "").split(/\r?\n/);
  let inSection = "";
  let done = [];
  let doing = [];
  let next = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (/^##\s*(Morning|Done)/i.test(trimmed)) {
      inSection = "done";
      continue;
    }
    if (/^##\s*(Afternoon|Doing|In progress)/i.test(trimmed)) {
      inSection = "doing";
      continue;
    }
    if (/^##\s*(Next|Loose ends|Follow-up)/i.test(trimmed)) {
      inSection = "next";
      continue;
    }
    if (!trimmed.startsWith("- ")) continue;

    const bullet = trimmed.slice(2).trim();
    if (!bullet) continue;

    if (inSection === "done") done.push(bullet);
    else if (inSection === "doing") doing.push(bullet);
    else if (inSection === "next") next.push(bullet);
    else if (/complet|finish|push|done/i.test(bullet)) done.push(bullet);
    else if (/work|build|setup|module/i.test(bullet)) doing.push(bullet);
    else next.push(bullet);
  }

  if (!done.length) done = ["(see notes for today)"];
  if (!doing.length) doing = ["(nothing flagged in progress)"];
  if (!next.length) next = ["Review notes and plan tomorrow"];

  return { done, doing, next };
}

function formatWrapup({ done, doing, next }, date, trigger = "web") {
  const stamp = new Date().toISOString();
  return [
    `# Daily Wrap-Up — ${date}`,
    "",
    "## Done",
    ...done.map((b) => `- ${b}`),
    "",
    "## Doing",
    ...doing.map((b) => `- ${b}`),
    "",
    "## Next",
    ...next.map((b) => `- ${b}`),
    "",
    "---",
    `*Generated by daily-wrap-up (trigger: ${trigger}) at ${stamp}*`,
  ].join("\n");
}

function runWrapup(notesText, options = {}) {
  const date =
    options.date ||
    new Date().toLocaleDateString("en-CA", { timeZone: "Africa/Nairobi" });
  const parsed = parseNotes(notesText);
  return formatWrapup(parsed, date, options.trigger || "web");
}

module.exports = { parseNotes, formatWrapup, runWrapup };
