#!/usr/bin/env bash
# Daily Wrap-Up — reads today's notes, writes summary to log/
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE="${WRAPUP_DATE:-$(date +%Y-%m-%d)}"
TRIGGER="${WRAPUP_TRIGGER:-manual}"
NOTES="$ROOT/notes/$DATE.md"
LOG="$ROOT/log/$DATE-wrapup.md"
PROOF_DIR="$ROOT/PROOF"

mkdir -p "$ROOT/log" "$PROOF_DIR"

if [[ ! -f "$NOTES" ]]; then
  echo "No notes file: $NOTES" >&2
  exit 1
fi

# Parse notes into done/doing/next heuristically
DONE=""
DOING=""
NEXT=""

in_section=""
while IFS= read -r line; do
  case "$line" in
    "## Morning"|"## Done"*)
      in_section="done" ;;
    "## Afternoon"|"## Doing"|"## In progress")
      in_section="doing" ;;
    "## Next"|"## Loose ends"|"## Follow-up")
      in_section="next" ;;
    "- "*)
      bullet="${line#- }"
      case "$in_section" in
        done)  DONE+="- $bullet"$'\n' ;;
        doing) DOING+="- $bullet"$'\n' ;;
        next)  NEXT+="- $bullet"$'\n' ;;
        *)
          if echo "$bullet" | grep -qiE 'complet|finish|push|done'; then
            DONE+="- $bullet"$'\n'
          elif echo "$bullet" | grep -qiE 'work|build|setup|module'; then
            DOING+="- $bullet"$'\n'
          else
            NEXT+="- $bullet"$'\n'
          fi
          ;;
      esac
      ;;
  esac
done < "$NOTES"

# Fallbacks if sections empty
[[ -z "$DONE" ]] && DONE="- (see notes for today)"$'\n'
[[ -z "$DOING" ]] && DOING="- (nothing flagged in progress)"$'\n'
[[ -z "$NEXT" ]] && NEXT="- Review notes and plan tomorrow"$'\n'

cat > "$LOG" <<EOF
# Daily Wrap-Up — $DATE

## Done
${DONE}
## Doing
${DOING}
## Next
${NEXT}
---
*Generated by daily-wrap-up (trigger: $TRIGGER) at $(date -Iseconds)*
EOF

echo "Wrote $LOG (trigger: $TRIGGER)"

# Append proof entry
PROOF_FILE="$PROOF_DIR/proof-log.txt"
echo "[$(date -Iseconds)] trigger=$TRIGGER output=$LOG" >> "$PROOF_FILE"
